app:
    version: 1.0.0
loggin:
    level:
        org: WARN
server:
    port: 5000
spring:
    datasource:
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USER}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
            show-sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
